language: node_js

services:
  - couchdb

node_js:
  - "stable"
script: npm run $COMMAND
before_script:
  - "npm install add-cors-to-couchdb"
  - "./node_modules/.bin/add-cors-to-couchdb"

env:
  matrix:
  - COMMAND=test
  - COMMAND=test-browser
  - COMMAND=test-coverage

branches:
  only:
  - master
